# @format

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish CI

on:
  push:
    branches: ["release"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CI checkout
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: CI setup
        run: yarn ci
      - name: CI build
        run: yarn build
      - name: Run tests
        run: yarn test
  publish:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
      - name: Publish checkout
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Publish setup
        run: yarn ci
      - name: Publish build
        run: yarn build
      - name: Publish to NPM
        run: yarn run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}